- name: Compile Frida Gadget (arm64)
        run: |
          # 1. 先跑官方脚本初始化子模块依赖
          python tools/ensure-submodules.py frida-core
          
          # 2. 【核心修复】强制把 frida-core 切换为你 Fork 仓库的最新代码
          cd subprojects/frida-core
          git remote set-url origin https://github.com/luyeguigen/frida-core.git
          git fetch origin main
          git checkout -f FETCH_HEAD
          echo "=========================================="
          echo "当前正在编译的 frida-core 提交记录："
          git log -1 --oneline
          echo "=========================================="
          cd ../..

          export FRIDA_PREFIX=$(pwd)/build/frida-android-arm64
          
          ./configure \
            "--prefix=$FRIDA_PREFIX" \
            --host=android-arm64 \
            --enable-portal \
            -- \
            -Dfrida-gum:devkits=gum,gumjs \
            -Dfrida-core:compiler_backend=enabled \
            -Dfrida-core:devkits=core

          make
          make install
