name: Build Frida Gadget

on:
  push:
    branches: [ "custom-frida" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [arm, arm64]

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl libglib2.0-dev pkg-config ninja-build flex bison
          pip install meson

      - name: Setup Android NDK
        uses: nkey/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build Frida Gadget (Android ${{ matrix.arch }})
        run: |
          make gadget-android-${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frida-gadget-android-${{ matrix.arch }}
          path: |
            build/frida-android-${{ matrix.arch }}/bin/frida-gadget*.so
            build/subprojects/frida-core/lib/gadget/frida-gadget*.so
            build/frida-android-${{ matrix.arch }}/lib/gadget/frida-gadget*.so
